source 'https://rubygems.org'

gem 'rails', '~> 8.1.2'

gem 'bootsnap', require: false
gem 'image_processing'
gem 'pg'
gem 'puma'

group :development, :test do
  gem 'sgcop', github: 'SonicGarden/sgcop', branch: 'main'
end
