source 'https://rubygems.org'

gem 'rails', '~> 8.1.2'

gem 'bootsnap', require: false
gem 'image_processing'
gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'jsonapi-serializer'

group :development, :test do
  gem 'sgcop', github: 'SonicGarden/sgcop', branch: 'main'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end
